apiVersion: apps/v1
kind: Deployment
metadata:
  name: alanp-2rep-nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: alanp-2rep-nginx-deployment
        image: nginx:latest
        ports:
        - containerPort: 80
